### ISSUE TITLE
Current version is wildly out of date from last release

### ISSUE THREAD

**Issue by sukima** [ember-cli/ember-exam#1309]
I attempted to update `@types/quinit` to get the current features like `test.each` only to discover I had to also update `ember-qunit` to version `8.1.1`

I then discovered that ember-exam pins 8.1.0 to the currently published version which was over a year ago while the version in `main` was updated 4 months ago. Is there something wrong with `main` that we are no longer able to publish releases to NPM?

How can we get the pinned dependency for `ember-qunit` to `8.1.1` for everyone to be able to use?

**Comment by NullVoxPopuli** [comment]
Since the `peerDependencies` are allowing _any_ version:
https://github.com/ember-cli/ember-exam/blob/main/package.json#L105-L109

It sounds like you're lockfile may be broken. Try deleting all the relevant packages from the lockfile and re-running install for your package manager.

Hope this helps!

**Comment by sukima** [comment]
I tried it still get a webpack error:

```
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: [application-name-redacted] needs ember-qunit satisfying 8.1.1, but we have version 8.1.0 because of ember-exam
        at WebpackBundler (ember-auto-import-webpack)
```
